### ISSUE TITLE
Add Collection PID beside title in dropdown list

### ISSUE THREAD

**Issue by bondjimbond** [contentmath/islandora_find_replace#1]
It's great that the proper collection title is used in the Collection dropdown, but unless each collection title is unique, this could result in devastating confusion.

Particularly in an multisite environment, it's highly likely that several collections might have the same or similar titles. (Example near miss: a mass change to "ECUAD Archival Photos" collection could have been mistakenly applied to "Archival Photos" collection.) 

It would forestall any confusion if, in the dropdown select list, the collection PID was displayed in parentheses beside the title.

**Comment by mitchmac** [comment]
Thanks for the issue report, the collection PID is now included in the form as of the latest commit.
